"""Tests for `jarvis digest` CLI command."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from click.testing import CliRunner

from openjarvis.agents.digest_store import DigestArtifact, DigestStore


def test_digest_command_exists():
    """The digest command is registered on the CLI."""
    from openjarvis.cli import cli

    runner = CliRunner()
    result = runner.invoke(cli, ["digest", "--help"])
    assert result.exit_code == 0
    assert "digest" in result.output.lower()


def test_digest_displays_cached(tmp_path):
    from openjarvis.cli import cli

    db_path = str(tmp_path / "digest.db")
    store = DigestStore(db_path=db_path)
    store.save(
        DigestArtifact(
            text="# Messages\nYou have 3 emails.\n# Calendar\n2 meetings today.",
            audio_path=Path("/nonexistent/audio.mp3"),
            sections={},
            sources_used=["gmail"],
            # Naive local time -- matches how MorningDigestAgent actually
            # stores it (plain datetime.now(), never made timezone-aware).
            generated_at=datetime.now(),
            model_used="test",
            voice_used="jarvis",
        )
    )
    store.close()

    runner = CliRunner()
    result = runner.invoke(cli, ["digest", "--text-only", "--db-path", db_path])
    assert result.exit_code == 0
    assert "3 emails" in result.output


def test_digest_no_cache(tmp_path):
    from openjarvis.cli import cli

    db_path = str(tmp_path / "empty.db")
    runner = CliRunner()
    result = runner.invoke(cli, ["digest", "--db-path", db_path])
    assert result.exit_code == 0
    assert "No digest for today" in result.output


def test_digest_fresh_reads_hermes(tmp_path):
    from unittest.mock import patch

    from openjarvis.cli import cli

    with patch(
        "openjarvis.agents.hermes_digest.fetch_today_text",
        return_value="Hermes digest text.",
    ) as fetch:
        result = CliRunner().invoke(
            cli, ["digest", "--fresh", "--db-path", str(tmp_path / "digest.db")]
        )

    assert result.exit_code == 0
    assert "generated by Hermes" in result.output
    assert "Hermes digest text." in result.output
    fetch.assert_called_once_with("general")


def test_digest_fresh_without_today(tmp_path):
    from unittest.mock import patch

    from openjarvis.cli import cli

    with patch("openjarvis.agents.hermes_digest.fetch_today_text", return_value=None):
        result = CliRunner().invoke(
            cli, ["digest", "--fresh", "--db-path", str(tmp_path / "digest.db")]
        )

    assert result.exit_code == 0
    assert "no digest for today" in result.output


def test_ask_good_morning_prints_hermes_digest_without_a_model():
    from unittest.mock import patch

    from openjarvis.cli import cli

    with (
        patch(
            "openjarvis.agents.hermes_digest.fetch_today_text",
            return_value="Hermes digest text.",
        ),
        patch("openjarvis.cli.ask.load_config") as load_config,
    ):
        result = CliRunner().invoke(cli, ["ask", "Good", "morning!"])

    assert result.exit_code == 0
    assert "Hermes digest text." in result.output
    load_config.assert_not_called()  # returned before any engine setup


def test_ask_good_morning_before_the_digest_is_out():
    from unittest.mock import patch

    from openjarvis.agents.hermes_digest import NOT_OUT_YET
    from openjarvis.cli import cli

    with patch("openjarvis.agents.hermes_digest.fetch_today_text", return_value=None):
        result = CliRunner().invoke(cli, ["ask", "--json", "good morning"])

    assert result.exit_code == 0
    assert NOT_OUT_YET in result.output
